Parameters:
  LatestAmiId:
    Description: "Latest AMI"
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: "t3.small"
      ImageId: !Ref "LatestAmiId"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-0e2bd68044a35b875  # Replace with your subnet ID
          GroupSet:
            - sg-0680b965517cf148c
