Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: justinsy-123
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      ImageId: ami-047126e50991d067b
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-0e2bd68044a35b875  # Replace with your subnet ID
          GroupSet:
            - sg-0680b965517cf148c
